version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
      - name: market_segment
        tests:
          - accepted_values:
              values: ['Automobile', 'Building', 'Furniture', 'Household', 'Machinery']

  - name: fct_orders
    columns:
      - name: order_key
        tests:
          - unique
          - not_null
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key
      - name: total_final_sales
        tests:
          - not_null